### ISSUE TITLE
error while running `ros2 run yolov5_ros2 yolo_detect_2d --ros-args -p device:=cpu -p image_topic:=/image`

### ISSUE THREAD

**Issue by wodehon** [fishros/yolov5_ros2#4]
> Traceback (most recent call last):
>   File "/home/duan/Code/ros2_planner/install/yolov5_ros2/lib/yolov5_ros2/yolo_detect_2d", line 33, in <module>
>     sys.exit(load_entry_point('yolov5-ros2==0.0.0', 'console_scripts', 'yolo_detect_2d')())
>   File "/home/duan/Code/ros2_planner/install/yolov5_ros2/lib/yolov5_ros2/yolo_detect_2d", line 25, in importlib_load_entry_point
>     return next(matches).load()
>   File "/home/duan/.local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 194, in load
>     module = import_module(match.group('module'))
>   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/home/duan/Code/ros2_planner/install/yolov5_ros2/lib/python3.6/site-packages/yolov5_ros2/yolo_detect_2d.py", line 8, in <module>
>     from torch import imag
>   File "/home/duan/anaconda3/envs/mytorch/lib/python3.8/site-packages/torch/__init__.py", line 210, in <module>
>     from torch._C import _initExtension
> ImportError: cannot import name '_initExtension'

I using ros2 dashing and anaconda with pytorch 1.11.0 torchvision 0.12.0

**Comment by JiaqiangZhang** [comment]
ROS2最好用原生的python，可以卸掉anaconda再试试

**Comment by wodehon** [comment]
> ROS2最好用原生的python，可以卸掉anaconda再试试

OK，搞定了，应该是Python版本不一致导致的。
